/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

drop schema if exists "proc" cascade;

CREATE SCHEMA "proc";{{ template "user_create_proc.sql".}} 
{{ template "user_update_proc.sql".}} 
{{ template "user_delete_proc.sql".}} 
{{ template "user_undo_delete_proc.sql".}} 
{{ template "apikey_create_proc.sql".}} 
{{ template "apikey_update_proc.sql".}} 
{{ template "apikey_delete_proc.sql".}} 
{{ template "apikey_undo_delete_proc.sql".}} 
{{ template "communicationchannel_create_proc.sql".}} 
{{ template "communicationchannel_update_proc.sql".}} 
{{ template "communicationchannel_delete_proc.sql".}} 
{{ template "communicationchannel_undo_delete_proc.sql".}} 
{{ template "messagetemplates_create_proc.sql".}} 
{{ template "messagetemplates_update_proc.sql".}} 
{{ template "messagetemplates_delete_proc.sql".}} 
{{ template "messagetemplates_undo_delete_proc.sql".}} 
{{ template "country_create_proc.sql".}} 
{{ template "country_update_proc.sql".}} 
{{ template "country_delete_proc.sql".}} 
{{ template "country_undo_delete_proc.sql".}} 
{{ template "site_create_proc.sql".}} 
{{ template "site_update_proc.sql".}} 
{{ template "site_delete_proc.sql".}} 
{{ template "site_undo_delete_proc.sql".}} 
{{ template "vendor_create_proc.sql".}} 
{{ template "vendor_update_proc.sql".}} 
{{ template "vendor_delete_proc.sql".}} 
{{ template "vendor_undo_delete_proc.sql".}} 
{{ template "task_create_proc.sql".}} 
{{ template "task_update_proc.sql".}} 
{{ template "task_delete_proc.sql".}} 
{{ template "task_undo_delete_proc.sql".}} 
{{ template "signal_create_proc.sql".}} 
{{ template "signal_update_proc.sql".}} 
{{ template "signal_delete_proc.sql".}} 
{{ template "signal_undo_delete_proc.sql".}} 
{{ template "servicecatalogue_create_proc.sql".}} 
{{ template "servicecatalogue_update_proc.sql".}} 
{{ template "servicecatalogue_delete_proc.sql".}} 
{{ template "servicecatalogue_undo_delete_proc.sql".}} 
{{ template "serviceorder_create_proc.sql".}} 
{{ template "serviceorder_update_proc.sql".}} 
{{ template "serviceorder_delete_proc.sql".}} 
{{ template "serviceorder_undo_delete_proc.sql".}} 
{{ template "service_create_proc.sql".}} 
{{ template "service_update_proc.sql".}} 
{{ template "service_delete_proc.sql".}} 
{{ template "service_undo_delete_proc.sql".}} 
{{ template "productionorder_create_proc.sql".}} 
{{ template "productionorder_update_proc.sql".}} 
{{ template "productionorder_delete_proc.sql".}} 
{{ template "productionorder_undo_delete_proc.sql".}} 
{{ template "meeting_create_proc.sql".}} 
{{ template "meeting_update_proc.sql".}} 
{{ template "meeting_delete_proc.sql".}} 
{{ template "meeting_undo_delete_proc.sql".}} 
{{ template "accesspass_create_proc.sql".}} 
{{ template "accesspass_update_proc.sql".}} 
{{ template "accesspass_delete_proc.sql".}} 
{{ template "accesspass_undo_delete_proc.sql".}} 
{{ template "accesspoint_create_proc.sql".}} 
{{ template "accesspoint_update_proc.sql".}} 
{{ template "accesspoint_delete_proc.sql".}} 
{{ template "accesspoint_undo_delete_proc.sql".}} 
{{ template "auditlog_create_proc.sql".}} 
{{ template "auditlog_update_proc.sql".}} 
{{ template "auditlog_delete_proc.sql".}} 
{{ template "auditlog_undo_delete_proc.sql".}} 
{{ template "visitor_create_proc.sql".}} 
{{ template "visitor_update_proc.sql".}} 
{{ template "visitor_delete_proc.sql".}} 
{{ template "visitor_undo_delete_proc.sql".}} 
{{ template "messagelog_create_proc.sql".}} 
{{ template "messagelog_update_proc.sql".}} 
{{ template "messagelog_delete_proc.sql".}} 
{{ template "messagelog_undo_delete_proc.sql".}} 
{{ template "transaction_create_proc.sql".}} 
{{ template "transaction_update_proc.sql".}} 
{{ template "transaction_delete_proc.sql".}} 
{{ template "transaction_undo_delete_proc.sql".}} 
{{ template "meetingroom_create_proc.sql".}} 
{{ template "meetingroom_update_proc.sql".}} 
{{ template "meetingroom_delete_proc.sql".}} 
{{ template "meetingroom_undo_delete_proc.sql".}} 
{{ template "building_create_proc.sql".}} 
{{ template "building_update_proc.sql".}} 
{{ template "building_delete_proc.sql".}} 
{{ template "building_undo_delete_proc.sql".}} 
{{ template "importdata_create_proc.sql".}} 
{{ template "importdata_update_proc.sql".}} 
{{ template "importdata_delete_proc.sql".}} 
{{ template "importdata_undo_delete_proc.sql".}} 
{{ template "tenant_create_proc.sql".}} 
{{ template "tenant_update_proc.sql".}} 
{{ template "tenant_delete_proc.sql".}} 
{{ template "tenant_undo_delete_proc.sql".}} 
{{ template "meetingrole_create_proc.sql".}} 
{{ template "meetingrole_update_proc.sql".}} 
{{ template "meetingrole_delete_proc.sql".}} 
{{ template "meetingrole_undo_delete_proc.sql".}} 
{{ template "graphcache_create_proc.sql".}} 
{{ template "graphcache_update_proc.sql".}} 
{{ template "graphcache_delete_proc.sql".}} 
{{ template "graphcache_undo_delete_proc.sql".}} 

