/*
---
keep: false
---
Generated by /Users/nielsgregersjohansen/kitchens/365admin-publish/scaffold/25-generatedatabase.ps1
Do not edit this file manually
*/

drop schema if exists "sync" cascade;

CREATE SCHEMA "sync";
{{ template "sharepoint-items.sql".}} 
