package officegraph

import (
	"log"
	"testing"
)

const token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IkNvdmhBb1EtN1hzbTFpa3ZRMzlHQk9KSEl0YVZIRmZVLW5UNTNwNmZJTGsiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyIsImtpZCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83OWRjMjI4Zi1jOGYyLTQwMTYtOGJmMC1iOTkwYjZjNzJlOTgvIiwiaWF0IjoxNzE5Mzg2NjUyLCJuYmYiOjE3MTkzODY2NTIsImV4cCI6MTcxOTM5MjMyNywiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhYQUFBQTRQaWFSSWZlcGhoU0JXMWtjUXBSbGpublV5aURFTk1DM0ZvTHczT3ZOaCs4TU84M0NBeFl4d213bUw1dE1KVG42SGhwWm56bGhpalNjcUorWE9reVJvVTJuZ3ZrVzhCVGJtRi9Bam8zOHZVPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiTWVldCIsImFwcGlkIjoiOGEwNDhhMGYtY2MxNi00ZGIzLWJjNmYtNzE1OGI2ZGQ2OTIyIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJKb2hhbnNlbiIsImdpdmVuX25hbWUiOiJOaWVscyIsImlkdHlwIjoidXNlciIsImlwYWRkciI6Ijc4LjE0My42Ni4xMzEiLCJuYW1lIjoiTmllbHMgR3JlZ2VycyBKb2hhbnNlbiIsIm9pZCI6IjliZWVmMjM1LTQ5ZDgtNDljZC04YzI4LWFhZDVhZWFiMDg0YiIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0xNzM2NDc2OC0xMDU2Mjg4ODM1LTM4NDkwMTc4OTctMjI4NTgiLCJwbGF0ZiI6IjUiLCJwdWlkIjoiMTAwM0JGRkQ4MEQxQTgyOSIsInJoIjoiMC5BUUlBanlMY2VmTElGa0NMOExtUXRzY3VtQU1BQUFBQUFBQUF3QUFBQUFBQUFBQUNBQkUuIiwic2NwIjoiQ2FsZW5kYXJzLlJlYWRXcml0ZSBNYWlsLlJlYWRCYXNpYyBvcGVuaWQgcHJvZmlsZSBVc2VyLlJlYWQgZW1haWwgQ2FsZW5kYXJzLlJlYWQiLCJzaWduaW5fc3RhdGUiOlsia21zaSJdLCJzdWIiOiJqTGpuSllNRjkxSFZNbWpRM2dFd3hKMTR3MVotOEZDRGZaWDkzM2Rpckw0IiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkVVIiwidGlkIjoiNzlkYzIyOGYtYzhmMi00MDE2LThiZjAtYjk5MGI2YzcyZTk4IiwidW5pcXVlX25hbWUiOiJuaWVscy5qb2hhbnNlbkBuZXhpZ3JvdXAuY29tIiwidXBuIjoibmllbHMuam9oYW5zZW5AbmV4aWdyb3VwLmNvbSIsInV0aSI6IjJvdWdKQWtYZVVhTW9WMlNCRzRIQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfaWRyZWwiOiIxIDE2IiwieG1zX3N0Ijp7InN1YiI6IlJuQlVfMEZESHRRRnlJeXlQYXpwZy12X3g0ZjFfZ09kd0RpbWRrSkE5ejQifSwieG1zX3RjZHQiOjEzMTc2MDQ1ODgsInhtc190ZGJyIjoiRVUifQ.mxD2sN7j8GPIN5YPWDEU5zyG_GpZCpKJ-ot6AlG9pIFFY438lGI8NDQeeu4RKJmUzBwMxiRktlsG4-Szg8LMV6QjMjoxSHhtIpk3fvplq-cUr0HexB0IEGhj4b-fTwedRuql7C13Ib4n2RbLX2oZM57XvnV4CqUHWhuDzA54LB2SewTpmK3e0wxEsWPi7PhSjGgzIavGQnB_Td8tcDhmRHSxjzhYJb6bB4t1I3aXVW1Q3d1VBaL_oCJIHAoFNUTzLjUJsJqu22i7TUF-ZP9fG2mWXPFRDNGJq_d_DWwIHz4uT3Z6Y-LBvyxY9Z8jlq6Vua21emXuYhs505eXCLIQ3w"

func TestDownload1(t *testing.T) {
	json, err := FetchGraphObject("https://graph.microsoft.com/v1.0/me/", token)
	if err != nil {
		t.Errorf("Expected nil, got %v", err)
	}
	log.Println(json)
}

func TestDownload2(t *testing.T) {
	err := CacheObject("tag", "actor", "https://graph.microsoft.com/v1.0/me/", token)
	if err != nil {
		t.Errorf("Expected nil, got %v", err)
	}

}

func TestDownload3(t *testing.T) {
	err := CacheObjects("tag", "actor", "https://graph.microsoft.com/v1.0/me/events?$select=subject,body,bodyPreview,organizer,attendees,start,end,location", token, 10)
	if err != nil {
		t.Errorf("Expected nil, got %v", err)
	}

}
